//
// AdminAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AdminAPI {

    /**
     Clear all data
     
     - parameter clearAllDataRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ClearAllDataResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func clearAllData(clearAllDataRequest: ClearAllDataRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ClearAllDataResponse {
        return try await clearAllDataWithRequestBuilder(clearAllDataRequest: clearAllDataRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Clear all data
     - POST /api/admin/clear-all
     - **DANGER:** Clears all data from the Redis database.  Requires explicit confirmation to proceed. Use with caution! 
     - parameter clearAllDataRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ClearAllDataResponse> 
     */
    open class func clearAllDataWithRequestBuilder(clearAllDataRequest: ClearAllDataRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ClearAllDataResponse> {
        let localVariablePath = "/api/admin/clear-all"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: clearAllDataRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ClearAllDataResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get metadata refresh status
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RefreshStatusResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRefreshMetadataStatus(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> RefreshStatusResponse {
        return try await getRefreshMetadataStatusWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get metadata refresh status
     - GET /api/admin/refresh-metadata/status
     - Returns the current status of the metadata refresh background task
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RefreshStatusResponse> 
     */
    open class func getRefreshMetadataStatusWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<RefreshStatusResponse> {
        let localVariablePath = "/api/admin/refresh-metadata/status"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RefreshStatusResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Refresh metadata for all tokens
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RefreshMetadataResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func refreshMetadata(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> RefreshMetadataResponse {
        return try await refreshMetadataWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Refresh metadata for all tokens
     - POST /api/admin/refresh-metadata
     - Triggers a background task to refresh metadata (symbol, name, decimals, logoURI)  for all existing tokens from Jupiter API. Useful for updating old tokens that  were added before automatic metadata fetching was implemented. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RefreshMetadataResponse> 
     */
    open class func refreshMetadataWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<RefreshMetadataResponse> {
        let localVariablePath = "/api/admin/refresh-metadata"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RefreshMetadataResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Replace all events
     
     - parameter replaceEventsRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ReplaceEvents200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func replaceEvents(replaceEventsRequest: ReplaceEventsRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ReplaceEvents200Response {
        return try await replaceEventsWithRequestBuilder(replaceEventsRequest: replaceEventsRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Replace all events
     - PUT /api/admin/events
     - Replaces all existing events with a new set of events. This completely overwrites the previous events.
     - parameter replaceEventsRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ReplaceEvents200Response> 
     */
    open class func replaceEventsWithRequestBuilder(replaceEventsRequest: ReplaceEventsRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ReplaceEvents200Response> {
        let localVariablePath = "/api/admin/events"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: replaceEventsRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ReplaceEvents200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
