//
// InvitesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class InvitesAPI {

    /**
     Verify and redeem an invite code
     
     - parameter authorization: (header) Authorization header containing the JWT token. Must start with \&quot;Bearer \&quot;. 
     - parameter verifyInviteCodeRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: VerifyInviteCodeResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func verifyInviteCode(authorization: String, verifyInviteCodeRequest: VerifyInviteCodeRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> VerifyInviteCodeResponse {
        return try await verifyInviteCodeWithRequestBuilder(authorization: authorization, verifyInviteCodeRequest: verifyInviteCodeRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Verify and redeem an invite code
     - POST /api/v1/invite/verify
     - Redeems a 7-character invite code for the current user and generates new invite codes.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter authorization: (header) Authorization header containing the JWT token. Must start with \&quot;Bearer \&quot;. 
     - parameter verifyInviteCodeRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<VerifyInviteCodeResponse> 
     */
    open class func verifyInviteCodeWithRequestBuilder(authorization: String, verifyInviteCodeRequest: VerifyInviteCodeRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<VerifyInviteCodeResponse> {
        let localVariablePath = "/api/v1/invite/verify"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: verifyInviteCodeRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Authorization": authorization.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VerifyInviteCodeResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
