//
// LanguagesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class LanguagesAPI {

    /**
     Get All Languages
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: LanguagesResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getLanguages(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> LanguagesResponse {
        return try await getLanguagesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get All Languages
     - GET /api/languages
     - Get list of all supported languages with support flags for auto-translation
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<LanguagesResponse> 
     */
    open class func getLanguagesWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<LanguagesResponse> {
        let localVariablePath = "/api/languages"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LanguagesResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
