//
// PricesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class PricesAPI {

    /**
     Get all price data
     
     - parameter address: (path) Solana token address 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetAllPricesResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getAllPrices(address: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetAllPricesResponse {
        return try await getAllPricesWithRequestBuilder(address: address, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get all price data
     - GET /api/tokens/{address}/prices
     - Returns all price data for a token in a single request.  Perfect for mobile apps - includes day (480 points, 3m), week (3360 points, 3m), month (1440 points, 30m), and year (~524+ points, 8H intervals) data. Note: Year data adjusts based on token creation date. 
     - parameter address: (path) Solana token address 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetAllPricesResponse> 
     */
    open class func getAllPricesWithRequestBuilder(address: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GetAllPricesResponse> {
        var localVariablePath = "/api/tokens/{address}/prices"
        let addressPreEscape = "\(APIHelper.mapValueToPathItem(address))"
        let addressPostEscape = addressPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{address}", with: addressPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetAllPricesResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter range
     */
    public enum ModelRange_getHistoricalPrices: String, Sendable, CaseIterable {
        case _1d = "1d"
        case _1w = "1w"
        case _1m = "1m"
        case _1y = "1y"
    }

    /**
     Get historical prices
     
     - parameter address: (path) Solana token address 
     - parameter range: (query) Time range for historical data (optional, default to ._1d)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetHistoricalPricesResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getHistoricalPrices(address: String, range: ModelRange_getHistoricalPrices? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetHistoricalPricesResponse {
        return try await getHistoricalPricesWithRequestBuilder(address: address, range: range, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get historical prices
     - GET /api/tokens/{address}/prices/historical
     - Returns historical price data for a token. Data is fetched from Birdeye API with aligned timestamps.
     - parameter address: (path) Solana token address 
     - parameter range: (query) Time range for historical data (optional, default to ._1d)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetHistoricalPricesResponse> 
     */
    open class func getHistoricalPricesWithRequestBuilder(address: String, range: ModelRange_getHistoricalPrices? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GetHistoricalPricesResponse> {
        var localVariablePath = "/api/tokens/{address}/prices/historical"
        let addressPreEscape = "\(APIHelper.mapValueToPathItem(address))"
        let addressPostEscape = addressPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{address}", with: addressPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "range": (wrappedValue: range?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetHistoricalPricesResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get latest price
     
     - parameter address: (path) Solana token address 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetRealtimePriceResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRealtimePrice(address: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetRealtimePriceResponse {
        return try await getRealtimePriceWithRequestBuilder(address: address, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get latest price
     - GET /api/tokens/{address}/prices/realtime
     - Returns the most recent price for a token from historical data. In production, prices are updated every 3 minutes.
     - parameter address: (path) Solana token address 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetRealtimePriceResponse> 
     */
    open class func getRealtimePriceWithRequestBuilder(address: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GetRealtimePriceResponse> {
        var localVariablePath = "/api/tokens/{address}/prices/realtime"
        let addressPreEscape = "\(APIHelper.mapValueToPathItem(address))"
        let addressPostEscape = addressPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{address}", with: addressPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRealtimePriceResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
