//
// SystemAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SystemAPI {

    /**
     Get indexing queue status
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetQueueStatusResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getQueueStatus(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetQueueStatusResponse {
        return try await getQueueStatusWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get indexing queue status
     - GET /api/indexing/queue
     - Returns the current status of the token indexing queue, including what's being processed and what's waiting.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetQueueStatusResponse> 
     */
    open class func getQueueStatusWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GetQueueStatusResponse> {
        let localVariablePath = "/api/indexing/queue"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetQueueStatusResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Health check
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: HealthCheckResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func healthCheck(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> HealthCheckResponse {
        return try await healthCheckWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Health check
     - GET /health
     - Returns the health status of the API and its dependencies
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<HealthCheckResponse> 
     */
    open class func healthCheckWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<HealthCheckResponse> {
        let localVariablePath = "/health"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HealthCheckResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
