//
// TokensAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class TokensAPI {

    /**
     Add token to index
     
     - parameter addTokenRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AddTokenResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addToken(addTokenRequest: AddTokenRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> AddTokenResponse {
        return try await addTokenWithRequestBuilder(addTokenRequest: addTokenRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Add token to index
     - POST /api/tokens
     - Adds a new token to the indexing queue. Historical prices will be fetched automatically.
     - parameter addTokenRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AddTokenResponse> 
     */
    open class func addTokenWithRequestBuilder(addTokenRequest: AddTokenRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<AddTokenResponse> {
        let localVariablePath = "/api/tokens"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addTokenRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AddTokenResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Add multiple tokens
     
     - parameter addTokensBatchRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AddTokensBatchResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addTokensBatch(addTokensBatchRequest: AddTokensBatchRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> AddTokensBatchResponse {
        return try await addTokensBatchWithRequestBuilder(addTokensBatchRequest: addTokensBatchRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Add multiple tokens
     - POST /api/tokens/batch
     - Adds multiple tokens to the indexing queue in a single request. Perfect for bulk imports. Maximum 50 tokens per request.  **Fast Response:** Returns immediately after validation.  Tokens are processed in the background. Use queue status endpoint to track progress.  Tokens will be processed sequentially, one at a time. 
     - parameter addTokensBatchRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AddTokensBatchResponse> 
     */
    open class func addTokensBatchWithRequestBuilder(addTokensBatchRequest: AddTokensBatchRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<AddTokensBatchResponse> {
        let localVariablePath = "/api/tokens/batch"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addTokensBatchRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AddTokensBatchResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get all indexed tokens
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetAllTokensResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getAllTokens(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetAllTokensResponse {
        return try await getAllTokensWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get all indexed tokens
     - GET /api/tokens
     - Returns a list of all tokens currently being tracked
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetAllTokensResponse> 
     */
    open class func getAllTokensWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GetAllTokensResponse> {
        let localVariablePath = "/api/tokens"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetAllTokensResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get specific token
     
     - parameter address: (path) Solana token address 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetTokenResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getToken(address: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetTokenResponse {
        return try await getTokenWithRequestBuilder(address: address, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get specific token
     - GET /api/tokens/{address}
     - Returns information about a specific indexed token
     - parameter address: (path) Solana token address 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetTokenResponse> 
     */
    open class func getTokenWithRequestBuilder(address: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GetTokenResponse> {
        var localVariablePath = "/api/tokens/{address}"
        let addressPreEscape = "\(APIHelper.mapValueToPathItem(address))"
        let addressPostEscape = addressPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{address}", with: addressPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetTokenResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Search tokens
     
     - parameter q: (query) Search query (minimum 2 characters) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SearchTokensResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func searchTokens(q: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> SearchTokensResponse {
        return try await searchTokensWithRequestBuilder(q: q, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Search tokens
     - GET /api/tokens/search
     - Search for tokens by name, symbol, or address. Returns matching tokens with their latest prices.
     - parameter q: (query) Search query (minimum 2 characters) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SearchTokensResponse> 
     */
    open class func searchTokensWithRequestBuilder(q: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<SearchTokensResponse> {
        let localVariablePath = "/api/tokens/search"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": (wrappedValue: q.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SearchTokensResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
