//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class UsersAPI {

    /**
     Complete a task
     
     - parameter authorization: (header) Authorization header containing the JWT token. Must start with \&quot;Bearer \&quot;. 
     - parameter id: (path) Task ID (UUID) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CompleteTaskResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func completeTask(authorization: String, id: UUID, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> CompleteTaskResponse {
        return try await completeTaskWithRequestBuilder(authorization: authorization, id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Complete a task
     - POST /api/v1/user/tasks/{id}/complete
     - Marks a specific task as completed for the current user.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter authorization: (header) Authorization header containing the JWT token. Must start with \&quot;Bearer \&quot;. 
     - parameter id: (path) Task ID (UUID) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CompleteTaskResponse> 
     */
    open class func completeTaskWithRequestBuilder(authorization: String, id: UUID, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<CompleteTaskResponse> {
        var localVariablePath = "/api/v1/user/tasks/{id}/complete"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Authorization": authorization.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CompleteTaskResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get user invite codes
     
     - parameter authorization: (header) Authorization header containing the JWT token. Must start with \&quot;Bearer \&quot;. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UserInviteCodesResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getUserInviteCodes(authorization: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> UserInviteCodesResponse {
        return try await getUserInviteCodesWithRequestBuilder(authorization: authorization, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get user invite codes
     - GET /api/v1/user/codes
     - Returns the current user's invite codes with usage metadata.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter authorization: (header) Authorization header containing the JWT token. Must start with \&quot;Bearer \&quot;. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UserInviteCodesResponse> 
     */
    open class func getUserInviteCodesWithRequestBuilder(authorization: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<UserInviteCodesResponse> {
        let localVariablePath = "/api/v1/user/codes"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Authorization": authorization.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserInviteCodesResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get user points
     
     - parameter authorization: (header) Authorization header containing the JWT token. Must start with \&quot;Bearer \&quot;. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UserPointsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getUserPoints(authorization: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> UserPointsResponse {
        return try await getUserPointsWithRequestBuilder(authorization: authorization, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get user points
     - GET /api/v1/user/points
     - Returns total points from completed tasks plus points from used invite codes.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter authorization: (header) Authorization header containing the JWT token. Must start with \&quot;Bearer \&quot;. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UserPointsResponse> 
     */
    open class func getUserPointsWithRequestBuilder(authorization: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<UserPointsResponse> {
        let localVariablePath = "/api/v1/user/points"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Authorization": authorization.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserPointsResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get user tasks
     
     - parameter authorization: (header) Authorization header containing the JWT token. Must start with \&quot;Bearer \&quot;. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UserTasksResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getUserTasks(authorization: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> UserTasksResponse {
        return try await getUserTasksWithRequestBuilder(authorization: authorization, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get user tasks
     - GET /api/v1/user/tasks
     - Returns all tasks with completion state for the current user.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter authorization: (header) Authorization header containing the JWT token. Must start with \&quot;Bearer \&quot;. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UserTasksResponse> 
     */
    open class func getUserTasksWithRequestBuilder(authorization: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<UserTasksResponse> {
        let localVariablePath = "/api/v1/user/tasks"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Authorization": authorization.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserTasksResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
