//
// AddTokenResponseQueue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddTokenResponseQueue: Sendable, Codable, ParameterConvertible, Hashable {

    /** Position in queue */
    public var position: Double
    /** Whether indexing is active */
    public var isProcessing: Bool
    /** Currently processing token */
    public var currentToken: String?

    public init(position: Double, isProcessing: Bool, currentToken: String?) {
        self.position = position
        self.isProcessing = isProcessing
        self.currentToken = currentToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case position
        case isProcessing
        case currentToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(position, forKey: .position)
        try container.encode(isProcessing, forKey: .isProcessing)
        try container.encode(currentToken, forKey: .currentToken)
    }
}

