//
// AddTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddTokenResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var data: IndexedToken
    public var message: String
    public var queue: AddTokenResponseQueue

    public init(success: Bool, data: IndexedToken, message: String, queue: AddTokenResponseQueue) {
        self.success = success
        self.data = data
        self.message = message
        self.queue = queue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case data
        case message
        case queue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(data, forKey: .data)
        try container.encode(message, forKey: .message)
        try container.encode(queue, forKey: .queue)
    }
}

