//
// AddTokensBatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddTokensBatchRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let tokensRule = ArrayRule(minItems: 1, maxItems: 50, uniqueItems: false)
    public var tokens: [AddTokensBatchRequestTokensInner]

    public init(tokens: [AddTokensBatchRequestTokensInner]) {
        self.tokens = tokens
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokens
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tokens, forKey: .tokens)
    }
}

