//
// AddTokensBatchResponseQueue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddTokensBatchResponseQueue: Sendable, Codable, ParameterConvertible, Hashable {

    /** Number of tokens in queue */
    public var length: Double
    /** Whether indexing is active */
    public var isProcessing: Bool
    /** Currently processing token */
    public var currentToken: String?

    public init(length: Double, isProcessing: Bool, currentToken: String?) {
        self.length = length
        self.isProcessing = isProcessing
        self.currentToken = currentToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case length
        case isProcessing
        case currentToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(length, forKey: .length)
        try container.encode(isProcessing, forKey: .isProcessing)
        try container.encode(currentToken, forKey: .currentToken)
    }
}

