//
// AddTokensBatchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddTokensBatchResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var data: AddTokensBatchResponseData
    /** Status message */
    public var message: String
    /** List of skipped tokens (already indexed or in queue) */
    public var skipped: [AddTokensBatchResponseSkippedInner]?
    /** List of rejected tokens (only if any were rejected) */
    public var rejected: [AddTokensBatchResponseRejectedInner]?
    public var queue: AddTokensBatchResponseQueue

    public init(success: Bool, data: AddTokensBatchResponseData, message: String, skipped: [AddTokensBatchResponseSkippedInner]? = nil, rejected: [AddTokensBatchResponseRejectedInner]? = nil, queue: AddTokensBatchResponseQueue) {
        self.success = success
        self.data = data
        self.message = message
        self.skipped = skipped
        self.rejected = rejected
        self.queue = queue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case data
        case message
        case skipped
        case rejected
        case queue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(data, forKey: .data)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(skipped, forKey: .skipped)
        try container.encodeIfPresent(rejected, forKey: .rejected)
        try container.encode(queue, forKey: .queue)
    }
}

