//
// AddTokensBatchRequestTokensInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddTokensBatchRequestTokensInner: Sendable, Codable, ParameterConvertible, Hashable {

    /** Solana token address */
    public var address: String
    /** Token symbol (optional) */
    public var symbol: String?
    /** Token name (optional) */
    public var name: String?

    public init(address: String, symbol: String? = nil, name: String? = nil) {
        self.address = address
        self.symbol = symbol
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case symbol
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encodeIfPresent(symbol, forKey: .symbol)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

