//
// AddTokensBatchResponseSkippedInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddTokensBatchResponseSkippedInner: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case skipped = "skipped"
    }
    public var address: String
    public var symbol: String?
    public var status: Status
    public var reason: String

    public init(address: String, symbol: String? = nil, status: Status, reason: String) {
        self.address = address
        self.symbol = symbol
        self.status = status
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case symbol
        case status
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encodeIfPresent(symbol, forKey: .symbol)
        try container.encode(status, forKey: .status)
        try container.encode(reason, forKey: .reason)
    }
}

