//
// AddTokensBatchResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddTokensBatchResponseData: Sendable, Codable, ParameterConvertible, Hashable {

    /** Number of NEW tokens accepted for indexing */
    public var accepted: Double
    /** Number of tokens already indexed or in queue */
    public var skipped: Double
    /** Number of tokens rejected (invalid format or errors) */
    public var rejected: Double
    /** Total tokens in request */
    public var total: Double

    public init(accepted: Double, skipped: Double, rejected: Double, total: Double) {
        self.accepted = accepted
        self.skipped = skipped
        self.rejected = rejected
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accepted
        case skipped
        case rejected
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accepted, forKey: .accepted)
        try container.encode(skipped, forKey: .skipped)
        try container.encode(rejected, forKey: .rejected)
        try container.encode(total, forKey: .total)
    }
}

