//
// ClearAllDataRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ClearAllDataRequest: Sendable, Codable, ParameterConvertible, Hashable {

    /** Must be exactly \"DELETE_ALL_DATA\" to proceed */
    public var confirm: String

    public init(confirm: String) {
        self.confirm = confirm
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case confirm
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(confirm, forKey: .confirm)
    }
}

