//
// EventToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EventToken: Sendable, Codable, ParameterConvertible, Hashable {

    /** Token address */
    public var id: String
    /** Token name */
    public var name: String
    /** Token symbol */
    public var symbol: String
    /** Token image URL */
    public var imageUrl: String

    public init(id: String, name: String, symbol: String, imageUrl: String) {
        self.id = id
        self.name = name
        self.symbol = symbol
        self.imageUrl = imageUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case symbol
        case imageUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(symbol, forKey: .symbol)
        try container.encode(imageUrl, forKey: .imageUrl)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EventToken: Identifiable {}
