//
// GetAllTokensResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAllTokensResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var data: [IndexedToken]
    /** Number of tokens */
    public var count: Double

    public init(success: Bool, data: [IndexedToken], count: Double) {
        self.success = success
        self.data = data
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case data
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(data, forKey: .data)
        try container.encode(count, forKey: .count)
    }
}

