//
// GetAllPricesResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAllPricesResponseData: Sendable, Codable, ParameterConvertible, Hashable {

    public var tokenAddress: String
    /** 480 price points with 3m intervals */
    public var day: [StoredPrice]
    /** 3360 price points with 3m intervals */
    public var week: [StoredPrice]
    /** 1440 price points with 30m intervals */
    public var month: [StoredPrice]
    /** Up to 1095 price points with 8H intervals (adjusts based on token creation date) */
    public var year: [StoredPrice]

    public init(tokenAddress: String, day: [StoredPrice], week: [StoredPrice], month: [StoredPrice], year: [StoredPrice]) {
        self.tokenAddress = tokenAddress
        self.day = day
        self.week = week
        self.month = month
        self.year = year
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenAddress
        case day
        case week
        case month
        case year
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tokenAddress, forKey: .tokenAddress)
        try container.encode(day, forKey: .day)
        try container.encode(week, forKey: .week)
        try container.encode(month, forKey: .month)
        try container.encode(year, forKey: .year)
    }
}

