//
// GetAllPricesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAllPricesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var data: GetAllPricesResponseData
    public var indexing: GetAllPricesResponseIndexing

    public init(success: Bool, data: GetAllPricesResponseData, indexing: GetAllPricesResponseIndexing) {
        self.success = success
        self.data = data
        self.indexing = indexing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case data
        case indexing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(data, forKey: .data)
        try container.encode(indexing, forKey: .indexing)
    }
}

