//
// GetAllPricesResponseIndexing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAllPricesResponseIndexing: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case complete = "complete"
        case indexing = "indexing"
        case queued = "queued"
        case pending = "pending"
    }
    /** Current indexing status */
    public var status: Status
    /** Human-readable status message */
    public var message: String?
    /** Timestamp of last indexing (milliseconds) */
    public var lastIndexed: Double

    public init(status: Status, message: String?, lastIndexed: Double) {
        self.status = status
        self.message = message
        self.lastIndexed = lastIndexed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case message
        case lastIndexed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(message, forKey: .message)
        try container.encode(lastIndexed, forKey: .lastIndexed)
    }
}

