//
// GetEvents200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetEvents200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var data: [ImportantEvent]
    /** Number of events returned */
    public var count: Int

    public init(success: Bool, data: [ImportantEvent], count: Int) {
        self.success = success
        self.data = data
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case data
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(data, forKey: .data)
        try container.encode(count, forKey: .count)
    }
}

