//
// GetHistoricalPricesResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetHistoricalPricesResponseData: Sendable, Codable, ParameterConvertible, Hashable {

    public enum ModelRange: String, Sendable, Codable, CaseIterable {
        case _1d = "1d"
        case _1w = "1w"
        case _1m = "1m"
        case _1y = "1y"
    }
    /** Token address */
    public var tokenAddress: String
    /** Time range */
    public var range: ModelRange
    /** Array of price points */
    public var prices: [StoredPrice]
    /** Number of price points */
    public var count: Double

    public init(tokenAddress: String, range: ModelRange, prices: [StoredPrice], count: Double) {
        self.tokenAddress = tokenAddress
        self.range = range
        self.prices = prices
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenAddress
        case range
        case prices
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tokenAddress, forKey: .tokenAddress)
        try container.encode(range, forKey: .range)
        try container.encode(prices, forKey: .prices)
        try container.encode(count, forKey: .count)
    }
}

