//
// GetTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTokenResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var data: IndexedToken

    public init(success: Bool, data: IndexedToken) {
        self.success = success
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(data, forKey: .data)
    }
}

