//
// HealthCheckResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HealthCheckResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case ok = "ok"
    }
    public var status: Status
    public var timestamp: Date
    /** Redis connection status */
    public var redis: Bool

    public init(status: Status, timestamp: Date, redis: Bool) {
        self.status = status
        self.timestamp = timestamp
        self.redis = redis
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case timestamp
        case redis
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(redis, forKey: .redis)
    }
}

