//
// HealthResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HealthResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var status: String
    public var timestamp: String
    public var database: Bool

    public init(status: String, timestamp: String, database: Bool) {
        self.status = status
        self.timestamp = timestamp
        self.database = database
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case timestamp
        case database
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(database, forKey: .database)
    }
}

