//
// ImportantEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImportantEvent: Sendable, Codable, ParameterConvertible, Hashable {

    /** Unique event identifier */
    public var id: String
    /** Event title */
    public var title: String
    /** Event subtitle/summary */
    public var subtitle: String
    /** Full event content in Markdown format */
    public var content: String
    /** Related tokens */
    public var tokens: [EventToken]
    /** ISO 8601 timestamp when the event was published */
    public var publishedAt: Date

    public init(id: String, title: String, subtitle: String, content: String, tokens: [EventToken], publishedAt: Date) {
        self.id = id
        self.title = title
        self.subtitle = subtitle
        self.content = content
        self.tokens = tokens
        self.publishedAt = publishedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case subtitle
        case content
        case tokens
        case publishedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(subtitle, forKey: .subtitle)
        try container.encode(content, forKey: .content)
        try container.encode(tokens, forKey: .tokens)
        try container.encode(publishedAt, forKey: .publishedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ImportantEvent: Identifiable {}
