//
// IndexedToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IndexedToken: Sendable, Codable, ParameterConvertible, Hashable {

    /** Solana token address */
    public var address: String
    /** Token symbol (e.g., SOL, USDC) */
    public var symbol: String?
    /** Token name (e.g., Solana, USD Coin) */
    public var name: String?
    /** Token decimals (e.g., 9 for SOL, 6 for USDC) */
    public var decimals: Double?
    /** Token logo image URL */
    public var logoURI: String?
    /** Timestamp when token was added (milliseconds) */
    public var addedAt: Double
    /** Timestamp of last historical price fetch (milliseconds) */
    public var lastIndexed: Double
    /** Whether the token is actively being tracked */
    public var isActive: Bool

    public init(address: String, symbol: String? = nil, name: String? = nil, decimals: Double? = nil, logoURI: String? = nil, addedAt: Double, lastIndexed: Double, isActive: Bool) {
        self.address = address
        self.symbol = symbol
        self.name = name
        self.decimals = decimals
        self.logoURI = logoURI
        self.addedAt = addedAt
        self.lastIndexed = lastIndexed
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case symbol
        case name
        case decimals
        case logoURI
        case addedAt
        case lastIndexed
        case isActive
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encodeIfPresent(symbol, forKey: .symbol)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(decimals, forKey: .decimals)
        try container.encodeIfPresent(logoURI, forKey: .logoURI)
        try container.encode(addedAt, forKey: .addedAt)
        try container.encode(lastIndexed, forKey: .lastIndexed)
        try container.encode(isActive, forKey: .isActive)
    }
}

