//
// InviteCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InviteCode: Sendable, Codable, ParameterConvertible, Hashable {

    public var code: String
    public var isUsed: Bool
    public var usedById: String?
    public var usedAt: String?
    public var createdAt: String

    public init(code: String, isUsed: Bool, usedById: String?, usedAt: String?, createdAt: String) {
        self.code = code
        self.isUsed = isUsed
        self.usedById = usedById
        self.usedAt = usedAt
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case isUsed
        case usedById
        case usedAt
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(isUsed, forKey: .isUsed)
        try container.encode(usedById, forKey: .usedById)
        try container.encode(usedAt, forKey: .usedAt)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

