//
// Language.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Language: Sendable, Codable, ParameterConvertible, Hashable {

    public var code: String
    public var name: String
    public var supported: Bool

    public init(code: String, name: String, supported: Bool) {
        self.code = code
        self.name = name
        self.supported = supported
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case name
        case supported
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(name, forKey: .name)
        try container.encode(supported, forKey: .supported)
    }
}

