//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModelErrorResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    /** Error message */
    public var error: String

    public init(success: Bool, error: String) {
        self.success = success
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(error, forKey: .error)
    }
}

