//
// QueueStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QueueStatus: Sendable, Codable, ParameterConvertible, Hashable {

    /** Whether a token is currently being processed */
    public var isProcessing: Bool
    /** Address of token currently being indexed */
    public var currentToken: String?
    /** Number of tokens waiting in queue */
    public var queueLength: Double
    /** List of tokens waiting to be processed */
    public var queue: [QueueItem]

    public init(isProcessing: Bool, currentToken: String?, queueLength: Double, queue: [QueueItem]) {
        self.isProcessing = isProcessing
        self.currentToken = currentToken
        self.queueLength = queueLength
        self.queue = queue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isProcessing
        case currentToken
        case queueLength
        case queue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isProcessing, forKey: .isProcessing)
        try container.encode(currentToken, forKey: .currentToken)
        try container.encode(queueLength, forKey: .queueLength)
        try container.encode(queue, forKey: .queue)
    }
}

