//
// RefreshStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefreshStatusResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    /** Whether a refresh is currently in progress */
    public var isRefreshing: Bool
    public var progress: RefreshMetadataResponseProgress

    public init(success: Bool, isRefreshing: Bool, progress: RefreshMetadataResponseProgress) {
        self.success = success
        self.isRefreshing = isRefreshing
        self.progress = progress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case isRefreshing
        case progress
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(isRefreshing, forKey: .isRefreshing)
        try container.encode(progress, forKey: .progress)
    }
}

