//
// RefreshMetadataResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefreshMetadataResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var message: String
    public var progress: RefreshMetadataResponseProgress

    public init(success: Bool, message: String, progress: RefreshMetadataResponseProgress) {
        self.success = success
        self.message = message
        self.progress = progress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case message
        case progress
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(message, forKey: .message)
        try container.encode(progress, forKey: .progress)
    }
}

