//
// RefreshInProgressResponseProgress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefreshInProgressResponseProgress: Sendable, Codable, ParameterConvertible, Hashable {

    public var current: Double?
    public var total: Double?
    public var updated: Double?
    public var failed: Double?

    public init(current: Double? = nil, total: Double? = nil, updated: Double? = nil, failed: Double? = nil) {
        self.current = current
        self.total = total
        self.updated = updated
        self.failed = failed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case total
        case updated
        case failed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(current, forKey: .current)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(updated, forKey: .updated)
        try container.encodeIfPresent(failed, forKey: .failed)
    }
}

