//
// RefreshMetadataResponseProgress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefreshMetadataResponseProgress: Sendable, Codable, ParameterConvertible, Hashable {

    /** Current token being processed */
    public var current: Double
    /** Total tokens to process */
    public var total: Double
    /** Successfully updated tokens */
    public var updated: Double
    /** Failed tokens */
    public var failed: Double

    public init(current: Double, total: Double, updated: Double, failed: Double) {
        self.current = current
        self.total = total
        self.updated = updated
        self.failed = failed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case total
        case updated
        case failed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(current, forKey: .current)
        try container.encode(total, forKey: .total)
        try container.encode(updated, forKey: .updated)
        try container.encode(failed, forKey: .failed)
    }
}

