//
// RefreshInProgressResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefreshInProgressResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var error: String
    public var progress: RefreshInProgressResponseProgress

    public init(success: Bool, error: String, progress: RefreshInProgressResponseProgress) {
        self.success = success
        self.error = error
        self.progress = progress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case error
        case progress
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(error, forKey: .error)
        try container.encode(progress, forKey: .progress)
    }
}

