//
// RegisterUserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RegisterUserResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var data: UserProfile
    public var timestamp: String

    public init(success: Bool, data: UserProfile, timestamp: String) {
        self.success = success
        self.data = data
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case data
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(data, forKey: .data)
        try container.encode(timestamp, forKey: .timestamp)
    }
}

