//
// RegisterUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RegisterUser: Sendable, Codable, ParameterConvertible, Hashable {

    public var nativeLanguage: String
    public var learningLanguage: String

    public init(nativeLanguage: String, learningLanguage: String) {
        self.nativeLanguage = nativeLanguage
        self.learningLanguage = learningLanguage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nativeLanguage
        case learningLanguage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nativeLanguage, forKey: .nativeLanguage)
        try container.encode(learningLanguage, forKey: .learningLanguage)
    }
}

