//
// ReplaceEvents200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReplaceEvents200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var message: String
    /** Number of events now available */
    public var count: Int

    public init(success: Bool, message: String, count: Int) {
        self.success = success
        self.message = message
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case message
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(message, forKey: .message)
        try container.encode(count, forKey: .count)
    }
}

