//
// SearchTokensResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchTokensResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var data: [SearchTokensResponseDataInner]
    /** Number of results */
    public var count: Double
    /** The search query used */
    public var query: String

    public init(success: Bool, data: [SearchTokensResponseDataInner], count: Double, query: String) {
        self.success = success
        self.data = data
        self.count = count
        self.query = query
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case data
        case count
        case query
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(data, forKey: .data)
        try container.encode(count, forKey: .count)
        try container.encode(query, forKey: .query)
    }
}

