//
// SearchTokensResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchTokensResponseDataInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var address: String
    public var symbol: String?
    public var name: String?
    public var addedAt: Double
    public var lastIndexed: Double
    public var isActive: Bool
    public var lastPrice: SearchTokensResponseDataInnerLastPrice?

    public init(address: String, symbol: String? = nil, name: String? = nil, addedAt: Double, lastIndexed: Double, isActive: Bool, lastPrice: SearchTokensResponseDataInnerLastPrice?) {
        self.address = address
        self.symbol = symbol
        self.name = name
        self.addedAt = addedAt
        self.lastIndexed = lastIndexed
        self.isActive = isActive
        self.lastPrice = lastPrice
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case symbol
        case name
        case addedAt
        case lastIndexed
        case isActive
        case lastPrice
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encodeIfPresent(symbol, forKey: .symbol)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(addedAt, forKey: .addedAt)
        try container.encode(lastIndexed, forKey: .lastIndexed)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(lastPrice, forKey: .lastPrice)
    }
}

