//
// SearchTokensResponseDataInnerLastPrice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchTokensResponseDataInnerLastPrice: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Source: String, Sendable, Codable, CaseIterable {
        case birdeye = "birdeye"
        case jupiter = "jupiter"
    }
    public var tokenAddress: String
    public var timestamp: Double
    public var price: Double
    public var source: Source

    public init(tokenAddress: String, timestamp: Double, price: Double, source: Source) {
        self.tokenAddress = tokenAddress
        self.timestamp = timestamp
        self.price = price
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenAddress
        case timestamp
        case price
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tokenAddress, forKey: .tokenAddress)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(price, forKey: .price)
        try container.encode(source, forKey: .source)
    }
}

