//
// StoredPrice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StoredPrice: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Source: String, Sendable, Codable, CaseIterable {
        case birdeye = "birdeye"
        case jupiter = "jupiter"
    }
    public enum Interval: String, Sendable, Codable, CaseIterable {
        case _3m = "3m"
        case _30m = "30m"
        case _8h = "8H"
    }
    /** Solana token address */
    public var tokenAddress: String
    /** Price in USD */
    public var price: Double
    /** Timestamp of the price (milliseconds) */
    public var timestamp: Double
    /** Data source */
    public var source: Source
    /** Time interval (only for historical prices, H = hours uppercase) */
    public var interval: Interval?

    public init(tokenAddress: String, price: Double, timestamp: Double, source: Source, interval: Interval? = nil) {
        self.tokenAddress = tokenAddress
        self.price = price
        self.timestamp = timestamp
        self.source = source
        self.interval = interval
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenAddress
        case price
        case timestamp
        case source
        case interval
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tokenAddress, forKey: .tokenAddress)
        try container.encode(price, forKey: .price)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(source, forKey: .source)
        try container.encodeIfPresent(interval, forKey: .interval)
    }
}

