//
// Task.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Task_: Sendable, Codable, ParameterConvertible, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case followX = "FOLLOW_X"
        case followDiscord = "FOLLOW_DISCORD"
        case connectSteam = "CONNECT_STEAM"
        case verifySteam = "VERIFY_STEAM"
        case place3Trades = "PLACE_3_TRADES"
    }
    public var id: String
    public var type: ModelType
    public var title: String
    public var description: String?
    public var points: Double
    public var isActive: Bool
    public var isCompleted: Bool?
    public var completedAt: String?

    public init(id: String, type: ModelType, title: String, description: String?, points: Double, isActive: Bool, isCompleted: Bool?, completedAt: String?) {
        self.id = id
        self.type = type
        self.title = title
        self.description = description
        self.points = points
        self.isActive = isActive
        self.isCompleted = isCompleted
        self.completedAt = completedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case title
        case description
        case points
        case isActive
        case isCompleted
        case completedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(title, forKey: .title)
        try container.encode(description, forKey: .description)
        try container.encode(points, forKey: .points)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(isCompleted, forKey: .isCompleted)
        try container.encode(completedAt, forKey: .completedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Task_: Identifiable {}
