//
// TokenAlreadyExistsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TokenAlreadyExistsResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var error: String
    public var data: IndexedToken

    public init(success: Bool, error: String, data: IndexedToken) {
        self.success = success
        self.error = error
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case error
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(error, forKey: .error)
        try container.encode(data, forKey: .data)
    }
}

