//
// UserProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserProfile: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int
    public var email: String
    public var nativeLanguage: String
    public var learningLanguage: String
    public var canUseAutoTranslation: Bool
    public var createdAt: String
    public var updatedAt: String

    public init(id: Int, email: String, nativeLanguage: String, learningLanguage: String, canUseAutoTranslation: Bool, createdAt: String, updatedAt: String) {
        self.id = id
        self.email = email
        self.nativeLanguage = nativeLanguage
        self.learningLanguage = learningLanguage
        self.canUseAutoTranslation = canUseAutoTranslation
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case nativeLanguage
        case learningLanguage
        case canUseAutoTranslation
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(email, forKey: .email)
        try container.encode(nativeLanguage, forKey: .nativeLanguage)
        try container.encode(learningLanguage, forKey: .learningLanguage)
        try container.encode(canUseAutoTranslation, forKey: .canUseAutoTranslation)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UserProfile: Identifiable {}
