//
// UserPointsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserPointsResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var points: Double
    public var timestamp: String

    public init(success: Bool, points: Double, timestamp: String) {
        self.success = success
        self.points = points
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case points
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(points, forKey: .points)
        try container.encode(timestamp, forKey: .timestamp)
    }
}

