//
// UserTasksResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserTasksResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var tasks: [UserTask]
    public var timestamp: String

    public init(success: Bool, tasks: [UserTask], timestamp: String) {
        self.success = success
        self.tasks = tasks
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case tasks
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(tasks, forKey: .tasks)
        try container.encode(timestamp, forKey: .timestamp)
    }
}

