//
// UserInviteCodesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserInviteCodesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var success: Bool
    public var codes: [InviteCode]
    public var timestamp: String

    public init(success: Bool, codes: [InviteCode], timestamp: String) {
        self.success = success
        self.codes = codes
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case codes
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(codes, forKey: .codes)
        try container.encode(timestamp, forKey: .timestamp)
    }
}

