//
// UserStatusData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserStatusData: Sendable, Codable, ParameterConvertible, Hashable {

    public var isRegistered: Bool
    public var needsOnboarding: Bool

    public init(isRegistered: Bool, needsOnboarding: Bool) {
        self.isRegistered = isRegistered
        self.needsOnboarding = needsOnboarding
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isRegistered
        case needsOnboarding
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isRegistered, forKey: .isRegistered)
        try container.encode(needsOnboarding, forKey: .needsOnboarding)
    }
}

